manifest:
  projects:
    - name: zmk
      url: https://github.com/zmkfirmware/zmk
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      url: https://github.com/kot149/zmk-pmw3610-driver
      revision: main
    - name: zmk-listeners
      url: https://github.com/ssbb/zmk-listeners
      revision: v1
    - name: zmk-rgbled-widget
      url: https://github.com/caksoylar/zmk-rgbled-widget
      revision: main
  self:
    path: config
