manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: sayu-hub
      url-base: https://github.com/sayu-hub
    - name: caksoylar  # <-- new entry
      url-base: https://github.com/caksoylar
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: sayu-hub
      revision: main
      path: modules/zmk-pmw3610-driver-sayu-hub
    - name: zmk-rgbled-widget  # <-- new entry
      remote: caksoylar
      revision: main
      path: modules/zmk-rgbled-widget
  self:
    path: config
